### PR TITLE
added help command and migrated to discord.py 2.0

### PR DESCRIPTION
**Pull request by Calciumcarbonate321**
Please check and lmk if there are any errors in this

### CODE REVIEW

**Comment by Calciumcarbonate321** [comment]
also add hacktoberfest label ( ´ ▽ ` )ﾉ

**Comment by Calciumcarbonate321** [comment]
What I have basically done is:
1.Removed the help command in main file and added a sub-classed one which is under the cogs dir
2.Changed some code that was breaking in discord.py 2.0
3.Refactored the get_prefix function and made it look more readable

**Comment by Calciumcarbonate321** [comment]
lmk if there is any error in the one that I did, good thing that there are no merge conflicts (~^.^)~

**Comment by Calciumcarbonate321** [comment]
image
image
image

**Comment by RKNpy** [comment]
> image
> image
> image
> 
>  custom emojis would look better in the buttons

woo thats really impresive, those table flips thing is not looking necessary, I recommend removing them, I will be adding role management cog till midnight.

**Comment by RKNpy** [comment]
> image
> image
> image
> 
>  custom emojis would look better in the buttons

woo thats really impresive, those table flips thing is not looking necessary, I recommend removing them, I will be adding role management cog till midnight.

**Comment by RKNpy** [comment]
woo thats really impresive, those table flips thing is not looking necessary, I recommend removing them, I will be adding role management cog till midnight.

**Comment by Calciumcarbonate321** [comment]
Okay, I'll remove them ASAP and will let you know, you can merge after that

**Comment by Calciumcarbonate321** [comment]
Done @RKNpy

**Comment by RKNpy** [comment]
Done thank you for the contribution @Calciumcarbonate321 :>

**Comment by Calciumcarbonate321** [comment]
Alright, I'll start working on more stuff

**Pull request merged**
