### PR TITLE
Reminder commands

### PR DESCRIPTION
**Pull request by GO-viper7**
So i added commands in main.py from my bot.
these commands are quite handy
It will ping you at the exact moment and also mention task
Screenshot (720)
Screenshot (721)
Screenshot (722)
Screenshot (724)

### CODE REVIEW

**Comment by RKNpy** [comment]
Thank you 😄

**Comment by GO-viper7** [comment]
Please dont forget to add tag of hacktoberfest.
Thank you. :)

**Comment by GO-viper7** [comment]
Yea lol, my bad!
And Should have directly code that help command  in main.py as it's a small one and irrelevant to other

**Comment by Calciumcarbonate321** [comment]
you don't actually have to hard code for it lol, just adding the help kwarg in command decorator is enough, this automated help command just makes our lives easier

**Pull request merged**
