### PR TITLE
Added some info commands

### PR DESCRIPTION
**Pull request by Calciumcarbonate321**
Let this be open for now, I'll add some more stuff and then you can merge

### CODE REVIEW

**Comment by RKNpy** [comment]
``

> Let this be open for now, I'll add some more stuff and then you can merge

please check line number `1128`, `1131` and `1243`. fix it

**Comment by Calciumcarbonate321** [comment]
resolved

**Comment by Calciumcarbonate321** [comment]
also you got any specific ideas ? I can implement them now

**Comment by Calciumcarbonate321** [comment]
image
got a cool automated invite yay

**Comment by Calciumcarbonate321** [comment]
ehh don't mind that last commit (；・∀・)

**Pull request merged**
